export const state = {
  view: "relationships",
  adminTab: "agent",
  agentRuntime: null,
  agentModels: [],
  agentModelNotice: "",
  capabilityPage: "overview",
  capabilityCategory: "create",
  capabilitySelectedId: "",
  externalCapabilities: null,
  companionContacts: null,
  wechatSnapshot: null,
  settingsTab: "general",
  settingsContacts: null,
  settingsContactsLoading: false,
  appUpdate: null,
  releaseAnnouncement: null,
  releaseAnnouncementOpen: false,
  systemStatus: null,
  onboardingInitialized: false,
  onboardingOpen: false,
  onboardingStep: "main-model",
  onboardingPersonaReady: false,
  onboardingError: "",
  globalNotice: "",
  settings: null,
  data: null,
  todayCalendar: null,
  todayMonth: "",
  todaySelectedDate: "",
  todayEventEditor: null,
  scheduleSnapshot: null,
  timelineFilter: "all",
  timelineQuery: "",
  relationshipPage: "conversation",
  unavailableFeature: null,
  relationshipFiles: null,
  relationshipFilePath: "",
  relationshipFilesError: "",
  relationshipContacts: null,
  conversationUnread: false,
  incomingConversationNotice: null,
  incomingVoiceCall: null,
  pendingIncomingVoiceCall: null,
  conversationCompactorSnapshot: null,
  conversationCompactorLoading: false,
  conversationCompactorError: "",
  agentJournalSnapshot: null,
  agentJournalLoading: false,
  agentJournalError: "",
  createPage: "overview",
  memoryStatus: null,
  memoryContactId: "",
  memoryContactSwitching: false,
};

export function isReady() {
  return state.data?.status === "ready";
}
