export const state = {
  view: "today",
  adminTab: "agent",
  apiConnectionManagerOpen: false,
  apiConnectionEditorOpen: false,
  apiConnectionEditingId: "",
  apiBindingPickerOpen: "",
  claudeCodeApi: null,
  claudeCodeModels: [],
  claudeCodeModelNotice: "",
  capabilityPage: "overview",
  capabilityCategory: "create",
  capabilitySelectedId: "",
  externalCapabilities: null,
  companionContacts: null,
  wechatSnapshot: null,
  siteAutomationSelectedSiteId: "",
  settingsTab: "general",
  onboardingInitialized: false,
  onboardingOpen: false,
  onboardingStep: "text-model",
  onboardingError: "",
  globalNotice: "",
  settings: null,
  data: null,
  todayCalendar: null,
  todayMonth: "",
  todaySelectedDate: "",
  todayEventEditor: null,
  scheduleSnapshot: null,
  timelineFilter: "all",
  timelineQuery: "",
  relationshipPage: "overview",
  relationshipFiles: null,
  relationshipFilePath: "",
  relationshipFilesError: "",
  relationshipContacts: null,
  conversationCompactorSnapshot: null,
  conversationCompactorLoading: false,
  conversationCompactorError: "",
  createPage: "overview",
  memoryStatus: null,
  memoryContactId: "",
  memoryContactSwitching: false,
};

export function isReady() {
  return state.data?.status === "ready";
}
