export const state = {
  view: "today",
  adminTab: "overview",
  apiConnectionManagerOpen: false,
  apiConnectionEditorOpen: false,
  apiConnectionEditingId: "",
  apiBindingPickerOpen: "",
  agentRuntime: null,
  claudeCodeApi: null,
  claudeCodeModels: [],
  claudeCodeModelNotice: "",
  runtimeSection: "overview",
  capabilityPage: "overview",
  capabilityCategory: "create",
  capabilitySelectedId: "",
  companionSessions: null,
  wechatSnapshot: null,
  siteAutomationSelectedSiteId: "",
  settingsTab: "general",
  onboardingInitialized: false,
  onboardingOpen: false,
  onboardingStep: "text-model",
  onboardingError: "",
  settings: null,
  data: null,
  todayCalendar: null,
  todayMonth: "",
  todaySelectedDate: "",
  todayEventEditor: null,
  scheduleSnapshot: null,
  timelineFilter: "all",
  timelineQuery: "",
  relationshipPage: "overview",
  relationshipFiles: null,
  relationshipFilePath: "",
  relationshipFilesError: "",
  relationshipContacts: null,
  createPage: "overview",
  memoryStatus: null,
  memoryQuery: "",
  memoryResult: null,
  memoryLibraryQuery: "",
  memoryLibraryStatus: "active",
  memoryLibrary: null,
  memoryEditing: null,
  memoryEditMode: false,
  memoryViewMode: "brain",
  memoryBrainGraph: null,
  memoryBrainLoading: false,
  memoryBrainSelectedId: "",
  memoryAttributionProposals: null,
  memoryAttributionLoading: false,
  memoryAttributionError: "",
  memoryAttributionResolvingId: "",
  memoryStructureProposals: null,
  memoryStructureLoading: false,
  memoryStructureError: "",
  memoryStructureResolvingId: "",
};

export function isReady() {
  return state.data?.status === "ready";
}
